# Generated by Django 6.0.6 on 2026-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('pengarang', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('rak', models.CharField(max_length=20)),
                ('stok', models.IntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='Aktif', max_length=15)),
            ],
        ),
    ]
