# Generated by Django 6.0.6 on 2026-06-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buku',
            table='perpus_buku',
        ),
        migrations.AlterModelTable(
            name='usersiswa',
            table='perpus_usersiswa',
        ),
    ]
