# Generated by Django 6.0.6 on 2026-06-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_alter_buku_table_alter_usersiswa_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='isbn',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='penerbit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='tahun_terbit',
            field=models.IntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status_pinjam', models.CharField(default='Dipinjam', max_length=20)),
                ('buku', models.ForeignKey(db_column='buku_id', on_delete=django.db.models.deletion.CASCADE, to='perpus.buku')),
                ('siswa', models.ForeignKey(db_column='siswa_id', on_delete=django.db.models.deletion.CASCADE, to='perpus.usersiswa')),
            ],
            options={
                'db_table': 'perpus_peminjaman',
            },
        ),
    ]
